import { l } from "../lang/Lang";

export default function buildSegments({
  mediaImages,
  rawSegments,
  transcriptionstatus,
  persons,
}) {
  const images = mediaImages;
  if (!images.length) return [];

  const idToIndex = new Map(images.map((m, idx) => [m.id, idx]));
  const personsById = new Map((persons || []).map((p) => [p.id, p]));

  const noRealSegments = !rawSegments || rawSegments.length === 0;

  const raw = noRealSegments
    ? [{ id: "__all__", startIndex: 0, __autoGenerated: true }]
    : rawSegments;

  // When no segments use title from first page if available
  let titleFirstPage = 
    mediaImages[0]?.title 
      ? mediaImages[0].title 
      : l("Alla sidor");

  const normalized = raw
    .map((s, i) => ({
      ...s,
      __order: i,
      startIndex: idToIndex.has(s.start_media_id)
        ? idToIndex.get(s.start_media_id)
        : Number.POSITIVE_INFINITY,
    }))
    .filter((s) => Number.isFinite(s.startIndex))
    .sort((a, b) => a.startIndex - b.startIndex);

  const built = normalized.map((s, i) => {
    const start = s.startIndex;
    const end =
      i < normalized.length - 1 ? normalized[i + 1].startIndex : images.length;
    const items = images.slice(start, end);

    const pageLabel =
      items.length === 1
        ? `${l("Sida")} ${start + 1}`
        : `${l("Sidor")} ${start + 1}–${end}`;

    const allReadyToTranscribe =
      items.length > 0 &&
      items.every((m) => m?.transcriptionstatus === "readytotranscribe");

    const customTitle = items[0]?.title;
    const autoTitle = `${l("Alla sidor")} (${items.length})`;

    const displayTitle = s.__autoGenerated
      ? autoTitle
      : allReadyToTranscribe
      ? `${pageLabel}: ${l("kan skrivas av")}`
      : customTitle
      ? `${pageLabel} – ${customTitle}`
      : pageLabel;

    const segmentPersons = (s.person_ids || [])
      .map((pid) => personsById.get(pid))
      .filter(Boolean);

    const segmentTxStatus = (() => {
      const pageStatuses = items
        .map((m) => m?.transcriptionstatus)
        .filter(Boolean);

      if (pageStatuses.some((st) => st === "readytotranscribe")) {
        return "readytotranscribe";
      }
      const nonPublished = pageStatuses.find((st) => st !== "published");
      if (nonPublished) return nonPublished;
      if (
        pageStatuses.length &&
        pageStatuses.every((st) => st === "published")
      ) {
        return "published";
      }
      return transcriptionstatus ?? null;
    })();

    return {
      id: s.id ?? `seg-${i}`,
      startIndex: start,
      items,
      title: displayTitle,
      segmentTranscriptionstatus: segmentTxStatus,
      persons: segmentPersons,
      autoGenerated: !!s.__autoGenerated,
      archive: {
        // we don’t really have pages per segment, so use media position as page
        page: Number.isFinite(start) ? start + 1 : null,
      },
    };
  });

  return built.length
    ? built
    : [
      {
        id: "__all__",
        startIndex: 0,
        items: images,
        title: `${titleFirstPage} (${images.length})`,
        segmentTranscriptionstatus: transcriptionstatus ?? null,
        persons: [],
        autoGenerated: true,
        archive: {
          page: images.length ? 1 : null,
        },
      },
    ];
}
