// Generated by Codex.
// Visual placeholder for the map while it's loading.
// Blue-green gradients and subtle grid pattern to evoke a map feel without showing actual data.
export default function MapLoadingPlaceholder() {
  return (
    <div
      className="absolute inset-0 z-[900] pointer-events-none"
      aria-hidden="true"
    >
      <div
        className="absolute inset-0"
        style={{
          background: 'var(--color-bg-gradient)',
        }}
      />
      <div
        className="absolute inset-0 opacity-40"
        style={{
          backgroundImage:
            'linear-gradient(0deg, rgb(var(--color-surface-rgb) / 0.4) 1px, transparent 1px), linear-gradient(90deg, rgb(var(--color-surface-rgb) / 0.4) 1px, transparent 1px)',
          backgroundSize: '34px 34px',
        }}
      />
      <div className="absolute right-8 top-8 h-10 w-10 rounded-full border-2 border-white/60 bg-white/50 shadow-sm" />
      <div className="absolute left-8 bottom-12 rounded-md border border-white/70 bg-white/70 px-3 py-2 text-sm text-gray-700 shadow-sm">
        Laddar karta...
      </div>
    </div>
  );
}
