// Generated by Codex.
// Visual placeholder for the map while it's loading.
// Blue-green gradients and subtle grid pattern to evoke a map feel without showing actual data.
export default function MapLoadingPlaceholder() {
  return (
    <div
      className="absolute inset-0 z-[900] pointer-events-none"
      aria-hidden="true"
    >
      <div
        className="absolute inset-0"
        style={{
          background:
            'radial-gradient(circle at 20% 20%, rgba(45, 212, 191, 0.28), transparent 40%), radial-gradient(circle at 80% 75%, rgba(14, 116, 144, 0.28), transparent 42%), linear-gradient(180deg, #e2e8f0 0%, #cbd5e1 100%)',
        }}
      />
      <div
        className="absolute inset-0 opacity-40"
        style={{
          backgroundImage:
            'linear-gradient(0deg, rgba(255,255,255,0.4) 1px, transparent 1px), linear-gradient(90deg, rgba(255,255,255,0.4) 1px, transparent 1px)',
          backgroundSize: '34px 34px',
        }}
      />
      <div className="absolute right-8 top-8 h-10 w-10 rounded-full border-2 border-white/60 bg-white/50 shadow-sm" />
      <div className="absolute left-8 bottom-12 rounded-md border border-white/70 bg-white/70 px-3 py-2 text-sm text-gray-700 shadow-sm">
        Laddar karta...
      </div>
    </div>
  );
}
