// Generated by Codex.
// Visual placeholder for the statistics section while it's loading.
// Uses teal and gray gradients with pulsing blocks to indicate loading content.
export default function StatisticsLoadingPlaceholder() {
  return (
    <div className="space-y-4">
      <div className="rounded-xl bg-gradient-to-br from-teal-50 to-cyan-50 border border-teal-100 p-4 shadow-sm">
        <div className="h-4 w-2/5 rounded bg-teal-200/60 animate-pulse mb-3" />
        <div className="h-10 w-1/2 rounded bg-teal-300/70 animate-pulse mb-2" />
        <div className="h-3 w-3/4 rounded bg-teal-200/60 animate-pulse" />
      </div>
      <div className="rounded-xl bg-white border border-gray-200 p-4 shadow-sm space-y-3">
        <div className="h-4 w-1/3 rounded bg-gray-200 animate-pulse" />
        <div className="h-8 w-full rounded bg-gray-100 animate-pulse" />
        <div className="h-8 w-11/12 rounded bg-gray-100 animate-pulse" />
        <div className="h-8 w-10/12 rounded bg-gray-100 animate-pulse" />
      </div>
    </div>
  );
}
