import PropTypes from 'prop-types';
import { useCallback, useId, useMemo } from 'react';
import config from '../../config';
import { l } from '../../lang/Lang';
import sanitizeHtml from '../../utils/sanitizeHtml';
import { isImageMedia } from '../../utils/mediaTypes';
import buildSegments from '../../utils/buildSegments';
import useTranscriptionAvailability from '../../hooks/useTranscriptionAvailability';
import TranscribeButton from '../TranscriptionPageByPageOverlay/ui/TranscribeButton';
import RecordViewThumbnails from '../RecordView/ui/RecordViewThumbnails';
import { computeStatus } from './utils/computeStatus';
import ContributorInfo, { PageContributor } from './ui/ContributorInfo';
import TranscribedText from './ui/TranscribedText';
import { StatusIndicator } from './ui/TranscriptionStatusIndicator';
import HighlightSwitcher from './ui/HighlightSwitcher';
import RecordSegment from './ui/RecordSegment';
import MediaCard from './ui/MediaCard';
import { useRecordHighlights } from './hooks/useRecordHighlights';

function RecordReader({ data, highlightData, mediaImageClickHandler }) {
  const {
    id: recordId, text, transcribedby, transcriptionstatus,
    media = [], segments: rawSegments = [], persons,
  } = data;
  const headingId = useId();
  const switchId = useId();
  const isTranscriptionAvailable = useTranscriptionAvailability();
  const imageEntries = useMemo(
    () => media.map((item, mediaIndex) => ({ item, mediaIndex }))
      .filter(({ item }) => isImageMedia(item)),
    [media],
  );
  const images = useMemo(() => imageEntries.map(({ item }) => item), [imageEntries]);
  const {
    highlight, setHighlight, highlightedMediaTexts, hasHighlights,
  } = useRecordHighlights({ highlightData, text, isPageByPage: true });
  const segments = useMemo(() => buildSegments({
    mediaImages: images, rawSegments, transcriptionstatus, persons,
  }), [images, rawSegments, transcriptionstatus, persons]);
  const hasRealSegments = segments.some((segment) => !segment.autoGenerated);
  const hasTranscribedText = images.some((item) => (
    item.text?.trim() && (item.transcriptionstatus || transcriptionstatus) !== 'readytotranscribe'
  ));
  const handleMediaClick = useCallback((item, index) => {
    mediaImageClickHandler(item, images, index);
  }, [images, mediaImageClickHandler]);
  const renderIndicator = useCallback((item) => (
    <StatusIndicator
      status={computeStatus({
        transcriptionstatus: item.transcriptionstatus || transcriptionstatus,
      })}
      size="md"
    />
  ), [transcriptionstatus]);
  const buildTextSide = (item, pageIndex) => {
    const { mediaIndex } = imageEntries[pageIndex];
    const pageStatus = item.transcriptionstatus || transcriptionstatus;
    if (item.text && pageStatus !== 'readytotranscribe') {
      const html = highlight && highlightedMediaTexts[String(mediaIndex)]
        ? highlightedMediaTexts[String(mediaIndex)] : item.text;
      return (
        <div className="space-y-2">
          <TranscribedText
            html={sanitizeHtml(html)}
            contentId={`${headingId}-text-${mediaIndex}`}
          />
          <PageContributor
            transcribedby={item.transcribedby || transcribedby}
            transcriptiondate={item.transcriptiondate || data.transcriptiondate}
            comment={item.comment}
          />
        </div>
      );
    }
    if (transcriptionstatus === 'accession') {
      return <p className="text-body">{l('Texten kan inte skrivas av.')}</p>;
    }
    if (pageStatus === 'readytotranscribe') {
      if (!isTranscriptionAvailable) return null;
      return (
        <div className="flex flex-col items-center gap-2 rounded-lg bg-surface-muted p-2">
          <p className="text-body">{l('Den här sidan kan skrivas av.')}</p>
          <TranscribeButton
            transcriptionstatus={transcriptionstatus}
            className="button button-primary"
            label={l('Skriv av')}
            recordId={recordId}
            random={false}
            initialPageIndex={pageIndex}
            initialPageSource={item.source}
          />
        </div>
      );
    }
    return (
      <p className="text-body">
        {l('Texten är ännu inte färdig – transkribering eller granskning pågår.')}
      </p>
    );
  };
  if (!images.length) return null;

  return (
    <section aria-labelledby={headingId} className="space-y-3">
      <div>
        <h2
          id={headingId}
          className="text-xl font-bold"
        >
          {l(hasTranscribedText ? 'Original och avskrift' : 'Originalbilder')}
        </h2>
        <div className="flex flex-wrap items-center gap-2">
          {hasHighlights && (
            <HighlightSwitcher id={switchId} highlight={highlight} setHighlight={setHighlight} />
          )}
        </div>
      </div>
      <RecordViewThumbnails
        images={images}
        onMediaClick={handleMediaClick}
        renderIndicator={renderIndicator}
      />
      <div className="space-y-3">
        {hasRealSegments ? segments.map((segment) => (
          <RecordSegment
            key={segment.id}
            title={segment.title}
            mediaItems={segment.items}
            startIndex={segment.startIndex}
            imageUrl={config.imageUrl}
            renderIndicator={renderIndicator}
            onMediaClick={handleMediaClick}
            buildTextSide={buildTextSide}
            defaultOpen
            segmentStatus={computeStatus({
              transcriptionstatus: segment.segmentTranscriptionstatus,
            })}
            persons={segment.persons}
          />
        )) : images.map((item, index) => (
          <MediaCard
            key={item.id || item.source}
            mediaItem={item}
            index={index}
            imageUrl={config.imageUrl}
            renderIndicator={renderIndicator}
            onMediaClick={handleMediaClick}
            right={buildTextSide(item, index)}
            headingLevel="h3"
          />
        ))}
      </div>
      <ContributorInfo
        transcribedby={transcribedby}
        comment={data.comment}
        transcriptiondate={data.transcriptiondate}
      />
    </section>
  );
}

const readerPropTypes = {
  data: PropTypes.object.isRequired,
  highlightData: PropTypes.object,
  mediaImageClickHandler: PropTypes.func.isRequired,
};
RecordReader.propTypes = readerPropTypes;

export default function RecordTextPanel({ data, highlightData, mediaImageClickHandler }) {
  return (
    <RecordReader
      key={data.id}
      data={data}
      highlightData={highlightData}
      mediaImageClickHandler={mediaImageClickHandler}
    />
  );
}
RecordTextPanel.propTypes = readerPropTypes;
